warframe/config/routes.rb
Rails.application.routes.draw do
  resources :items, only: [:index, :action]
  get 'items/', to: 'items#index' 
  root to: 'items#index'
  get 'about' => 'items#about'
  get 'items/:id', to: 'items#action', as: 'items_info', id: /\d+/
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

warframe/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

warframe/app/models/enemy.rb
class Enemy < ApplicationRecord
    has_many :enemy_items
    has_many :items, through: :enemy_items

    validates :name, presence: true
end

warframe/app/models/enemy_item.rb
class EnemyItem < ApplicationRecord
  belongs_to :item
  belongs_to :enemy
  belongs_to :rarity
end

warframe/app/models/item.rb
class Item < ApplicationRecord
    has_many :enemy_items
    has_many :enemies, through: :enemy_items

    validates :name, :description, :price, presence: true
    validates :price, numericality: true
    

end

warframe/app/models/rarity.rb
class Rarity < ApplicationRecord
    validates :name, presence: true
end

warframe/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

warframe/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  #The index action
  def index
    @items = Item.paginate(:page => params[:page], per_page: 10)
    @enemies = Enemy.all 
    @rarities = Rarity.all 
    @enemy_items = EnemyItem.all 
  end

  #The show action
  def action
    @item = Item.find(params[:id])
    @enemy_item = EnemyItem.where(item_id: params[:id])
    @enemy = Enemy.all
  end

  def about
  end
end

warframe/app/helpers/application_helper.rb
module ApplicationHelper
end

warframe/app/helpers/items_helper.rb
module ItemsHelper
end

warframe/app/views/items/about.html.erb
<h1>This is my ERD</h1>
<p>
    This website is designed for users to be able to look through the different items in warframe and to provide minor informations about them. I used a warframe API, to populate most of the items, and Faker to fill up the database with more information.
    As you can see, I made 4 tables(Enemy_item, Enemy, Item, Rarity). I needed 4 in order for me to have multiple drops. Having the relationship between Item, Enemy_item and Enemy, I was able to have multiple items dropping from an enemy and vice versa.
    The plan was to populate the database using the API and Faker before taking the name of the item to use as a link, in the website, for users to click on. 
</p>
<p><%= image_tag("erd.JPG", :alt => "Project Erd") %></p>

warframe/app/views/items/action.html.erb
<h2>This item is called <%= @item.name %></h2>

<ul>
    <li>
        Item description: <%= @item.description %>
    </li>
    <li>
        Item price: <%= @item.price %>
    </li>
    <li>
        Item Drop Chance: 
        <% @enemy_item.each do |e| %>
            <ul>
                <li>
                    <%= e.enemyItemDropChance %> on <% @enemy.where(:id => e.enemy_id).each do |enemy| %>
                                            <%= enemy.name %>
                                            <% end %>
                </li>
            </ul>
        <% end %>
    </li>
</ul>

warframe/app/views/items/index.html.erb
<h2>List of items</h2>
<%= will_paginate @posts %>
<ul>
    <% @items.each do |info| %>
        <%# The only reason I have the id popping up is for you to be able to know the ids of the items %>
        <li><%= info.id %>    
            <%= link_to info.name, items_info_path(info) %>
        </li>
    <% end %>
</ul>

warframe/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Warframe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Warframe Items</h1>
      <div class="topnav">
        <%= link_to 'Home', root_path %>
        <%= link_to 'About', 'about' %>
      </div>
    </header>
    <%= yield %>
    <footer>
      <p>Copyleft 2018</p>
    </footer>
  </body>
</html>